<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_</name>
   <tag></tag>
   <elementGuidId>c3fd0087-fa09-4315-b501-385b0ad38ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='620_21_0_5c2efb64-3efd-d5a5-ffc7-4aa2fc888ff4']/span/i/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#620_21_0_5c2efb64-3efd-d5a5-ffc7-4aa2fc888ff4 > span.ms-Button-flexContainer.flexContainer-164 > i.ms-Button-icon.icon-184 > span.FLwLv > i.Q0K3G.___198tor0.f14t3ns0.fne0op0.fg4l7m0.fmd4ok8.f1sxfq9t</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f8dc5476-413f-4c95-b77a-ce74dafe9090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t</value>
      <webElementGuid>39d0e2f0-e72b-4c97-ae62-ced1766c4928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>7ca88e0a-4a7f-40e7-b768-5c04311661d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e9a0f452-f4c3-4296-a75f-adb16f495a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f63be5c7-112b-47af-b9b1-f65c680442f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;620_21_0_5c2efb64-3efd-d5a5-ffc7-4aa2fc888ff4&quot;)/span[@class=&quot;ms-Button-flexContainer flexContainer-164&quot;]/i[@class=&quot;ms-Button-icon icon-184&quot;]/span[@class=&quot;FLwLv&quot;]/i[@class=&quot;Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t&quot;]</value>
      <webElementGuid>9e242bbb-bccd-40c0-ab5b-e7c65cbb5a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='620_21_0_5c2efb64-3efd-d5a5-ffc7-4aa2fc888ff4']/span/i/span/i</value>
      <webElementGuid>67e227fa-12f2-426c-bd0a-2e2b6650c811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change case'])[1]/following::i[10]</value>
      <webElementGuid>6e40fcf8-3805-4ee6-a716-f59c993eff6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>130aed8a-7f76-472a-a3a0-11784e490c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/button/span/i/span/i</value>
      <webElementGuid>e3115b38-0528-4a91-a938-60f1b6f77657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = '' or . = '')]</value>
      <webElementGuid>d7af8a4d-eef2-400f-a5ca-0556f53fd5ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
