<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_New mail</name>
   <tag></tag>
   <elementGuidId>75adb4ce-c650-4e65-b8d5-c14cfe5c9c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='id__124']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id__124</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>53a7ec36-5979-441f-9048-62b78fe3f5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textContainer label-186</value>
      <webElementGuid>152ef308-2ad4-42cb-8785-277d66c03765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id__124</value>
      <webElementGuid>9c198673-74e8-4727-8f04-c8658c764bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New mail</value>
      <webElementGuid>12240f9d-c5e0-44ed-8788-111aaabfa77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id__124&quot;)</value>
      <webElementGuid>2c150fa0-713a-43e3-ba5a-9dff41280d96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id__124']</value>
      <webElementGuid>67ec6da7-5953-4499-b2ef-05f890e65b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='innerRibbonContainer']/div/div/div/div/div[2]/div/div/span/button/span/span/span</value>
      <webElementGuid>49bf104e-0238-4ff9-887f-24436b6854e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[2]/following::span[7]</value>
      <webElementGuid>4f336193-8877-4980-bf77-35be8e97497b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/following::span[8]</value>
      <webElementGuid>d59b2337-2f8c-42fc-a17e-9d4067b295ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[6]</value>
      <webElementGuid>d143cabe-c54b-4f59-b71c-825c4678fe1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New mail']/parent::*</value>
      <webElementGuid>0f098618-46c5-4605-8a19-ca3afb44da20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span/span/span</value>
      <webElementGuid>397d3537-f6a4-452f-a90b-ff81c522380a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'id__124' and (text() = 'New mail' or . = 'New mail')]</value>
      <webElementGuid>6522b5c7-6696-4506-8caf-c9890a974a8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
