<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send</name>
   <tag></tag>
   <elementGuidId>e34c5deb-f5fd-4ee4-a711-8f41999b9455</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='id__217']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id__217</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2636c03b-d8d2-4f48-b639-61699e6a60d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-label label-167</value>
      <webElementGuid>621543d2-6f0a-439e-b69f-1653a786756d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id__217</value>
      <webElementGuid>a1a97104-6f31-4e52-9f1e-aed7b6153efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>2fdbea88-1cb7-48a0-ae00-0bd5112d18a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id__217&quot;)</value>
      <webElementGuid>33be0829-ecf8-49f6-ae5d-eae5c4716620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='id__217']</value>
      <webElementGuid>4452bbe3-c020-44cc-bd2f-58dc05f3b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='docking_InitVisiblePart_0']/div/div[2]/div/div/span/button/span/span/span</value>
      <webElementGuid>94bf9ca0-d34f-4c10-aa54-5f6289773eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Alt+Down for more options'])[1]/following::span[4]</value>
      <webElementGuid>b6ddecb3-ef5e-4f6c-9989-8722eaf577c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy your empty inbox.'])[1]/following::span[5]</value>
      <webElementGuid>27d9cf19-7cb1-4c29-aee1-954a9559bca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::span[3]</value>
      <webElementGuid>e2296e82-674e-4e20-9e80-790b5e099362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='outlook_E03D1AE5D7545708@outlook.com'])[1]/preceding::span[3]</value>
      <webElementGuid>29f31dd1-b3cb-4216-b734-fe66c83509c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>eb188b08-3b7d-4983-adf2-b03d0ca67b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button/span/span/span</value>
      <webElementGuid>482f7da3-94de-464f-904b-de0f7d3e7e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'id__217' and (text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>c7436854-eadc-4d58-ac97-54867adba4e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
